# ============================================================================
# Log level for code generate agent (debug/info/warning/error)
# ============================================================================
log_level: info

# ============================================================================
# The temperature of the model, defaults to 0
# ============================================================================
temperature: 0.3

# ============================================================================
# The max_tokens of the model, defaults to 1024
# ============================================================================
max_tokens: 1024

# ============================================================================
# The timeout of the model , defaults to 300
# ============================================================================
timeout: 600

# ============================================================================
# The model_max_retries of the model, defaults to 10
# ============================================================================
model_max_retries: 20

# ============================================================================
# The max_retries of the tool, defaults to 3
# ============================================================================
tool_max_retries: 3

# ============================================================================
# The messages count when summarization is triggered, defaults to 10
# ============================================================================
summarization_trigger_messages: 6

# ============================================================================
# The tokens count when summarization is triggered, defaults to 100
# ============================================================================
summarization_trigger_tokens: 500

# ============================================================================
# Mode type (openai/xiaomi/deepseek/qwen/glm), defaults to deepseek
# currently, only OpenAI is supported, Anthropic has not been supported
# ============================================================================
model_type: xiaomi

# ============================================================================
# Model type for embedding (qwen_embedding), defaults to qwen_embedding
# ============================================================================
embedding_model_type: qwen_embedding

# ============================================================================
# Whether use user memory or not
# ============================================================================
user_memory: false

# ============================================================================
# Seconds to wait before processing queued updates (debounce), defaults to 10
# ============================================================================
debounce_seconds: 3

# ============================================================================
# Minimum confidence threshold for storing facts, defaults to 0.7
# ============================================================================
fact_confidence_threshold: 0.7

# ============================================================================
# Maximum number of facts to store, defaults to 50
# ============================================================================
max_facts: 20

# ============================================================================
# Maximum tokens to use for memory injection
# ============================================================================
max_injection_tokens: 1000

# ============================================================================
# Maximum model cycle for one request, defaults to 10
# ============================================================================
model_cycle_max: 20

# ============================================================================
# The index of es, defaults to rag_chunk_index
# ============================================================================
es_index: rag_chunk_index

# ============================================================================
# The address of es defaults to http://localhost:9200
# ============================================================================
es_address: http://localhost:9200

# ============================================================================
# Minimum score for rerank score, defaults to 0.8
# ============================================================================
rerank_score_min: 0.8

# ============================================================================
# Print thinking process, whether print the thinking process, defaults to true
# ============================================================================
print_thinking_process: true

# ============================================================================
# Where open tool call trace, true/false, defaults to false
# ============================================================================
open_tool_call_trace: true