from typing import Any

from pydantic import Field

from backend.sub_agent.code_generate.plan_and_execute.response import PlannerResponse

class GraphPlannerResponse(PlannerResponse):
    graph: Any= Field(description="The graph generated by the planner")