from typing import List, Any

from pydantic import  Field

from backend.sub_agent.code_generate.plan_and_execute.response import PlannerResponse

class DynamicStepPlannerResponse(PlannerResponse):
    steps: List[Any] = Field(description="The steps generated by the planner.")

    # execute_steps: Any = Field(description="The steps to be executed.")